### ISSUE TITLE
Expected string default value for '--verbose'; got false (boolean)

### ISSUE THREAD

**Issue by Startouf** [mirakui/ec2ssh#40]
I get the following error when running `ec2ssh init`.

```
Expected string default value for '--verbose'; got false (boolean)
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/ec2ssh-3.1.0/lib/ec2ssh/migrator.rb:28:in `check_version': Ec2ssh::InvalidDotfile (Ec2ssh::InvalidDotfile)
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/ec2ssh-3.1.0/lib/ec2ssh/cli.rb:96:in `check_dotfile_version'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/ec2ssh-3.1.0/lib/ec2ssh/cli.rb:15:in `init'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/gems/ec2ssh-3.1.0/bin/ec2ssh:4:in `<top (required)>'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/bin/ec2ssh:22:in `load'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/bin/ec2ssh:22:in `<main>'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Cyril/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

My credentials file looks like
```
[default]
aws_access_key_id=********
aws_secret_access_key=*******

[Cyril]
aws_access_key_id=******
aws_secret_access_key=*******
```

**Comment by mirakui** [comment]
Thank you for your report. This bug was fixed in `3.1.1`.
